// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"encoding/json"
	"fmt"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Classification.
const (
	Confidential Classification = "confidential"
	Internal     Classification = "internal"
	Public       Classification = "public"
	Restricted   Classification = "restricted"
)

// Valid indicates whether the value is a known member of the Classification enum.
func (e Classification) Valid() bool {
	switch e {
	case Confidential:
		return true
	case Internal:
		return true
	case Public:
		return true
	case Restricted:
		return true
	default:
		return false
	}
}

// Defines values for ContextPackSchemaVersion.
const (
	ThinkpixelMemContextPackV1 ContextPackSchemaVersion = "thinkpixel.mem.context-pack.v1"
)

// Valid indicates whether the value is a known member of the ContextPackSchemaVersion enum.
func (e ContextPackSchemaVersion) Valid() bool {
	switch e {
	case ThinkpixelMemContextPackV1:
		return true
	default:
		return false
	}
}

// Defines values for CreateMemorySpaceScopeType.
const (
	CreateMemorySpaceScopeTypeAgent        CreateMemorySpaceScopeType = "agent"
	CreateMemorySpaceScopeTypeCustom       CreateMemorySpaceScopeType = "custom"
	CreateMemorySpaceScopeTypeOrganization CreateMemorySpaceScopeType = "organization"
	CreateMemorySpaceScopeTypeTeam         CreateMemorySpaceScopeType = "team"
	CreateMemorySpaceScopeTypeUser         CreateMemorySpaceScopeType = "user"
	CreateMemorySpaceScopeTypeWorkspace    CreateMemorySpaceScopeType = "workspace"
)

// Valid indicates whether the value is a known member of the CreateMemorySpaceScopeType enum.
func (e CreateMemorySpaceScopeType) Valid() bool {
	switch e {
	case CreateMemorySpaceScopeTypeAgent:
		return true
	case CreateMemorySpaceScopeTypeCustom:
		return true
	case CreateMemorySpaceScopeTypeOrganization:
		return true
	case CreateMemorySpaceScopeTypeTeam:
		return true
	case CreateMemorySpaceScopeTypeUser:
		return true
	case CreateMemorySpaceScopeTypeWorkspace:
		return true
	default:
		return false
	}
}

// Defines values for EvidenceReferenceKind.
const (
	ArEvent                EvidenceReferenceKind = "ar-event"
	ArRun                  EvidenceReferenceKind = "ar-run"
	ArSession              EvidenceReferenceKind = "ar-session"
	ExternalDocument       EvidenceReferenceKind = "external-document"
	ImportedMemory         EvidenceReferenceKind = "imported-memory"
	ModelExtractionRequest EvidenceReferenceKind = "model-extraction-request"
	TgInvocation           EvidenceReferenceKind = "tg-invocation"
	TgResult               EvidenceReferenceKind = "tg-result"
	UserMessage            EvidenceReferenceKind = "user-message"
	WsComponent            EvidenceReferenceKind = "ws-component"
	WsGeneration           EvidenceReferenceKind = "ws-generation"
)

// Valid indicates whether the value is a known member of the EvidenceReferenceKind enum.
func (e EvidenceReferenceKind) Valid() bool {
	switch e {
	case ArEvent:
		return true
	case ArRun:
		return true
	case ArSession:
		return true
	case ExternalDocument:
		return true
	case ImportedMemory:
		return true
	case ModelExtractionRequest:
		return true
	case TgInvocation:
		return true
	case TgResult:
		return true
	case UserMessage:
		return true
	case WsComponent:
		return true
	case WsGeneration:
		return true
	default:
		return false
	}
}

// Defines values for MemorySpaceScopeType.
const (
	MemorySpaceScopeTypeAgent        MemorySpaceScopeType = "agent"
	MemorySpaceScopeTypeCustom       MemorySpaceScopeType = "custom"
	MemorySpaceScopeTypeOrganization MemorySpaceScopeType = "organization"
	MemorySpaceScopeTypeTeam         MemorySpaceScopeType = "team"
	MemorySpaceScopeTypeUser         MemorySpaceScopeType = "user"
	MemorySpaceScopeTypeWorkspace    MemorySpaceScopeType = "workspace"
)

// Valid indicates whether the value is a known member of the MemorySpaceScopeType enum.
func (e MemorySpaceScopeType) Valid() bool {
	switch e {
	case MemorySpaceScopeTypeAgent:
		return true
	case MemorySpaceScopeTypeCustom:
		return true
	case MemorySpaceScopeTypeOrganization:
		return true
	case MemorySpaceScopeTypeTeam:
		return true
	case MemorySpaceScopeTypeUser:
		return true
	case MemorySpaceScopeTypeWorkspace:
		return true
	default:
		return false
	}
}

// Defines values for MemorySpaceState.
const (
	MemorySpaceStateActive    MemorySpaceState = "active"
	MemorySpaceStateDeleted   MemorySpaceState = "deleted"
	MemorySpaceStateDeleting  MemorySpaceState = "deleting"
	MemorySpaceStateSuspended MemorySpaceState = "suspended"
)

// Valid indicates whether the value is a known member of the MemorySpaceState enum.
func (e MemorySpaceState) Valid() bool {
	switch e {
	case MemorySpaceStateActive:
		return true
	case MemorySpaceStateDeleted:
		return true
	case MemorySpaceStateDeleting:
		return true
	case MemorySpaceStateSuspended:
		return true
	default:
		return false
	}
}

// Defines values for MemoryStatus.
const (
	MemoryStatusActive      MemoryStatus = "active"
	MemoryStatusDeleted     MemoryStatus = "deleted"
	MemoryStatusDisputed    MemoryStatus = "disputed"
	MemoryStatusExpired     MemoryStatus = "expired"
	MemoryStatusQuarantined MemoryStatus = "quarantined"
	MemoryStatusSuperseded  MemoryStatus = "superseded"
	MemoryStatusWithdrawn   MemoryStatus = "withdrawn"
)

// Valid indicates whether the value is a known member of the MemoryStatus enum.
func (e MemoryStatus) Valid() bool {
	switch e {
	case MemoryStatusActive:
		return true
	case MemoryStatusDeleted:
		return true
	case MemoryStatusDisputed:
		return true
	case MemoryStatusExpired:
		return true
	case MemoryStatusQuarantined:
		return true
	case MemoryStatusSuperseded:
		return true
	case MemoryStatusWithdrawn:
		return true
	default:
		return false
	}
}

// Defines values for MemoryType.
const (
	Claim              MemoryType = "claim"
	Episode            MemoryType = "episode"
	Lesson             MemoryType = "lesson"
	Outcome            MemoryType = "outcome"
	ProcedureCandidate MemoryType = "procedure-candidate"
	Relationship       MemoryType = "relationship"
)

// Valid indicates whether the value is a known member of the MemoryType enum.
func (e MemoryType) Valid() bool {
	switch e {
	case Claim:
		return true
	case Episode:
		return true
	case Lesson:
		return true
	case Outcome:
		return true
	case ProcedureCandidate:
		return true
	case Relationship:
		return true
	default:
		return false
	}
}

// Defines values for OperationState.
const (
	Accepted  OperationState = "accepted"
	Failed    OperationState = "failed"
	Running   OperationState = "running"
	Succeeded OperationState = "succeeded"
)

// Valid indicates whether the value is a known member of the OperationState enum.
func (e OperationState) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Failed:
		return true
	case Running:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// Defines values for RetrievalRequestSchemaVersion.
const (
	ThinkpixelMemRetrievalRequestV1 RetrievalRequestSchemaVersion = "thinkpixel.mem.retrieval-request.v1"
)

// Valid indicates whether the value is a known member of the RetrievalRequestSchemaVersion enum.
func (e RetrievalRequestSchemaVersion) Valid() bool {
	switch e {
	case ThinkpixelMemRetrievalRequestV1:
		return true
	default:
		return false
	}
}

// Defines values for SourceKind.
const (
	AgentObservation       SourceKind = "agent-observation"
	ExplicitUserAssertion  SourceKind = "explicit-user-assertion"
	ImportedExternalMemory SourceKind = "imported-external-memory"
	ModelInference         SourceKind = "model-inference"
	SystemDerived          SourceKind = "system-derived"
	VerifiedToolOutput     SourceKind = "verified-tool-output"
	WorkspaceObservation   SourceKind = "workspace-observation"
)

// Valid indicates whether the value is a known member of the SourceKind enum.
func (e SourceKind) Valid() bool {
	switch e {
	case AgentObservation:
		return true
	case ExplicitUserAssertion:
		return true
	case ImportedExternalMemory:
		return true
	case ModelInference:
		return true
	case SystemDerived:
		return true
	case VerifiedToolOutput:
		return true
	case WorkspaceObservation:
		return true
	default:
		return false
	}
}

// Defines values for SourceTrust.
const (
	High      SourceTrust = "high"
	Low       SourceTrust = "low"
	Medium    SourceTrust = "medium"
	Untrusted SourceTrust = "untrusted"
	Verified  SourceTrust = "verified"
)

// Valid indicates whether the value is a known member of the SourceTrust enum.
func (e SourceTrust) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	case Untrusted:
		return true
	case Verified:
		return true
	default:
		return false
	}
}

// Defines values for WarningCode.
const (
	WarningCodeDisputed      WarningCode = "disputed"
	WarningCodeLowTrust      WarningCode = "low-trust"
	WarningCodeOversizedItem WarningCode = "oversized-item"
	WarningCodePoisonRisk    WarningCode = "poison-risk"
	WarningCodeStale         WarningCode = "stale"
	WarningCodeTruncated     WarningCode = "truncated"
)

// Valid indicates whether the value is a known member of the WarningCode enum.
func (e WarningCode) Valid() bool {
	switch e {
	case WarningCodeDisputed:
		return true
	case WarningCodeLowTrust:
		return true
	case WarningCodeOversizedItem:
		return true
	case WarningCodePoisonRisk:
		return true
	case WarningCodeStale:
		return true
	case WarningCodeTruncated:
		return true
	default:
		return false
	}
}

// Classification defines model for Classification.
type Classification string

// ContextItem defines model for ContextItem.
type ContextItem struct {
	Classification  Classification         `json:"classification"`
	Confidence      float32                `json:"confidence"`
	Content         map[string]interface{} `json:"content"`
	Evidence        []EvidenceReference    `json:"evidence"`
	MemoryId        UUIDv7                 `json:"memory_id"`
	RetrievalReason string                 `json:"retrieval_reason"`
	Revision        int                    `json:"revision"`
	SourceTrust     SourceTrust            `json:"source_trust"`
	Status          MemoryStatus           `json:"status"`
	Type            MemoryType             `json:"type"`
	Warnings        *[]Warning             `json:"warnings,omitempty"`
}

// ContextPack defines model for ContextPack.
type ContextPack struct {
	Budget struct {
		EstimatedTokens int `json:"estimated_tokens"`
		ItemCount       int `json:"item_count"`
		ItemLimit       int `json:"item_limit"`
		TokenLimit      int `json:"token_limit"`
	} `json:"budget"`
	CreatedAt     Timestamp                `json:"created_at"`
	Id            UUIDv7                   `json:"id"`
	Items         []ContextItem            `json:"items"`
	PolicyVersion string                   `json:"policy_version"`
	SchemaVersion ContextPackSchemaVersion `json:"schema_version"`
	Warnings      []Warning                `json:"warnings"`
}

// ContextPackSchemaVersion defines model for ContextPack.SchemaVersion.
type ContextPackSchemaVersion string

// Correction defines model for Correction.
type Correction struct {
	Content          map[string]interface{} `json:"content"`
	Evidence         *[]EvidenceReference   `json:"evidence,omitempty"`
	ExpectedRevision int                    `json:"expected_revision"`
	Reason           string                 `json:"reason"`
}

// CreateEpisode defines model for CreateEpisode.
type CreateEpisode struct {
	Classification Classification       `json:"classification"`
	Evidence       *[]EvidenceReference `json:"evidence,omitempty"`
	MemorySpaceId  UUIDv7               `json:"memory_space_id"`
	OccurredFrom   Timestamp            `json:"occurred_from"`
	OccurredUntil  *time.Time           `json:"occurred_until,omitempty"`
	Summary        string               `json:"summary"`
	Title          string               `json:"title"`
}

// CreateMemory defines model for CreateMemory.
type CreateMemory struct {
	Classification Classification         `json:"classification"`
	Content        map[string]interface{} `json:"content"`
	Evidence       *[]EvidenceReference   `json:"evidence,omitempty"`
	MemorySpaceId  UUIDv7                 `json:"memory_space_id"`
	Type           MemoryType             `json:"type"`
	ValidFrom      *time.Time             `json:"valid_from,omitempty"`
	ValidUntil     *time.Time             `json:"valid_until,omitempty"`
}

// CreateMemorySpace defines model for CreateMemorySpace.
type CreateMemorySpace struct {
	Classification    Classification             `json:"classification"`
	Name              string                     `json:"name"`
	Residency         []string                   `json:"residency"`
	RetentionPolicyId string                     `json:"retention_policy_id"`
	ScopeSubject      string                     `json:"scope_subject"`
	ScopeType         CreateMemorySpaceScopeType `json:"scope_type"`
	StrategyId        string                     `json:"strategy_id"`
}

// CreateMemorySpaceScopeType defines model for CreateMemorySpace.ScopeType.
type CreateMemorySpaceScopeType string

// EvidenceReference defines model for EvidenceReference.
type EvidenceReference struct {
	Classification   Classification        `json:"classification"`
	Digest           *string               `json:"digest,omitempty"`
	Id               UUIDv7                `json:"id"`
	ImmutableVersion *string               `json:"immutable_version,omitempty"`
	Kind             EvidenceReferenceKind `json:"kind"`
	ObservedAt       Timestamp             `json:"observed_at"`
	SourceId         string                `json:"source_id"`
	SourceTrust      SourceTrust           `json:"source_trust"`
}

// EvidenceReferenceKind defines model for EvidenceReference.Kind.
type EvidenceReferenceKind string

// ForgetRequest defines model for ForgetRequest.
type ForgetRequest struct {
	Reason   string `json:"reason"`
	Selector struct {
		DataSubjectId *string `json:"data_subject_id,omitempty"`
		MemoryId      *UUIDv7 `json:"memory_id,omitempty"`
		MemorySpaceId *UUIDv7 `json:"memory_space_id,omitempty"`
		SourceId      *string `json:"source_id,omitempty"`
		SubjectId     *string `json:"subject_id,omitempty"`
	} `json:"selector"`
}

// IngestionEvent defines model for IngestionEvent.
type IngestionEvent struct {
	Classification  Classification         `json:"classification"`
	Content         map[string]interface{} `json:"content"`
	Evidence        *[]EvidenceReference   `json:"evidence,omitempty"`
	ExternalEventId string                 `json:"external_event_id"`
	MemorySpaceId   UUIDv7                 `json:"memory_space_id"`
	OccurredAt      Timestamp              `json:"occurred_at"`
	SourceKind      SourceKind             `json:"source_kind"`
	SourceService   string                 `json:"source_service"`
}

// Memory defines model for Memory.
type Memory struct {
	Classification Classification         `json:"classification"`
	Confidence     float32                `json:"confidence"`
	Content        map[string]interface{} `json:"content"`
	Evidence       *[]EvidenceReference   `json:"evidence,omitempty"`
	Id             UUIDv7                 `json:"id"`
	MemorySpaceId  UUIDv7                 `json:"memory_space_id"`
	RecordedAt     Timestamp              `json:"recorded_at"`
	Revision       int                    `json:"revision"`
	SourceKind     SourceKind             `json:"source_kind"`
	SourceTrust    SourceTrust            `json:"source_trust"`
	Status         MemoryStatus           `json:"status"`
	Type           MemoryType             `json:"type"`
	ValidFrom      *time.Time             `json:"valid_from,omitempty"`
	ValidUntil     *time.Time             `json:"valid_until,omitempty"`
}

// MemorySpace defines model for MemorySpace.
type MemorySpace struct {
	Classification    Classification       `json:"classification"`
	CreatedAt         Timestamp            `json:"created_at"`
	Id                UUIDv7               `json:"id"`
	Name              string               `json:"name"`
	Residency         []string             `json:"residency"`
	RetentionPolicyId string               `json:"retention_policy_id"`
	ScopeSubject      string               `json:"scope_subject"`
	ScopeType         MemorySpaceScopeType `json:"scope_type"`
	State             MemorySpaceState     `json:"state"`
	StrategyId        string               `json:"strategy_id"`
	UpdatedAt         Timestamp            `json:"updated_at"`
}

// MemorySpaceScopeType defines model for MemorySpace.ScopeType.
type MemorySpaceScopeType string

// MemorySpaceState defines model for MemorySpace.State.
type MemorySpaceState string

// MemoryStatus defines model for MemoryStatus.
type MemoryStatus string

// MemoryType defines model for MemoryType.
type MemoryType string

// Operation defines model for Operation.
type Operation struct {
	AcceptedAt Timestamp      `json:"accepted_at"`
	Id         UUIDv7         `json:"id"`
	State      OperationState `json:"state"`
}

// OperationState defines model for Operation.State.
type OperationState string

// Problem defines model for Problem.
type Problem struct {
	Detail               *string                `json:"detail,omitempty"`
	Instance             *string                `json:"instance,omitempty"`
	RequestId            *string                `json:"request_id,omitempty"`
	Status               int                    `json:"status"`
	Title                string                 `json:"title"`
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Profile defines model for Profile.
type Profile struct {
	BuiltAt Timestamp `json:"built_at"`
	Fields  map[string]struct {
		Confidence  float32     `json:"confidence"`
		MemoryIds   []UUIDv7    `json:"memory_ids"`
		SourceTrust SourceTrust `json:"source_trust"`
		UpdatedAt   Timestamp   `json:"updated_at"`
		Value       interface{} `json:"value"`
	} `json:"fields"`
	Id       UUIDv7                 `json:"id"`
	SchemaId UUIDv7                 `json:"schema_id"`
	Subject  map[string]interface{} `json:"subject"`
}

// ProfileSchema defines model for ProfileSchema.
type ProfileSchema struct {
	Fields  map[string]interface{} `json:"fields"`
	Id      UUIDv7                 `json:"id"`
	Name    string                 `json:"name"`
	Version string                 `json:"version"`
}

// Reason defines model for Reason.
type Reason struct {
	Reason string `json:"reason"`
}

// RetrievalRequest defines model for RetrievalRequest.
type RetrievalRequest struct {
	AsOf                  *time.Time                    `json:"as_of,omitempty"`
	ClassificationCeiling *Classification               `json:"classification_ceiling,omitempty"`
	Debug                 *bool                         `json:"debug,omitempty"`
	Goal                  *string                       `json:"goal,omitempty"`
	ItemBudget            int                           `json:"item_budget"`
	MemorySpaceIds        []UUIDv7                      `json:"memory_space_ids"`
	MemoryTypes           *[]MemoryType                 `json:"memory_types,omitempty"`
	Query                 string                        `json:"query"`
	SchemaVersion         RetrievalRequestSchemaVersion `json:"schema_version"`
	TokenBudget           int                           `json:"token_budget"`
}

// RetrievalRequestSchemaVersion defines model for RetrievalRequest.SchemaVersion.
type RetrievalRequestSchemaVersion string

// SourceKind defines model for SourceKind.
type SourceKind string

// SourceTrust defines model for SourceTrust.
type SourceTrust string

// Timestamp defines model for Timestamp.
type Timestamp = time.Time

// UUIDv7 defines model for UUIDv7.
type UUIDv7 = openapi_types.UUID

// Warning defines model for Warning.
type Warning struct {
	Code    WarningCode `json:"code"`
	Message string      `json:"message"`
}

// WarningCode defines model for Warning.Code.
type WarningCode string

// Cursor defines model for Cursor.
type Cursor = string

// ID defines model for ID.
type ID = UUIDv7

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// Limit defines model for Limit.
type Limit = int

// CreateEpisodeParams defines parameters for CreateEpisode.
type CreateEpisodeParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// StreamEventsParams defines parameters for StreamEvents.
type StreamEventsParams struct {
	LastEventID *string `json:"Last-Event-ID,omitempty"`
}

// IngestEventParams defines parameters for IngestEvent.
type IngestEventParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ForgetParams defines parameters for Forget.
type ForgetParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListMemoriesParams defines parameters for ListMemories.
type ListMemoriesParams struct {
	MemorySpaceId UUIDv7  `form:"memory_space_id" json:"memory_space_id"`
	Cursor        *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit         *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateMemoryParams defines parameters for CreateMemory.
type CreateMemoryParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ForgetMemoryParams defines parameters for ForgetMemory.
type ForgetMemoryParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CorrectMemoryParams defines parameters for CorrectMemory.
type CorrectMemoryParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListMemorySpacesParams defines parameters for ListMemorySpaces.
type ListMemorySpacesParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateMemorySpaceParams defines parameters for CreateMemorySpace.
type CreateMemorySpaceParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// DeleteMemorySpaceParams defines parameters for DeleteMemorySpace.
type DeleteMemorySpaceParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// RetrieveContextJSONRequestBody defines body for RetrieveContext for application/json ContentType.
type RetrieveContextJSONRequestBody = RetrievalRequest

// CreateEpisodeJSONRequestBody defines body for CreateEpisode for application/json ContentType.
type CreateEpisodeJSONRequestBody = CreateEpisode

// IngestEventJSONRequestBody defines body for IngestEvent for application/json ContentType.
type IngestEventJSONRequestBody = IngestionEvent

// ForgetJSONRequestBody defines body for Forget for application/json ContentType.
type ForgetJSONRequestBody = ForgetRequest

// CreateMemoryJSONRequestBody defines body for CreateMemory for application/json ContentType.
type CreateMemoryJSONRequestBody = CreateMemory

// CorrectMemoryJSONRequestBody defines body for CorrectMemory for application/json ContentType.
type CorrectMemoryJSONRequestBody = Correction

// QuarantineMemoryJSONRequestBody defines body for QuarantineMemory for application/json ContentType.
type QuarantineMemoryJSONRequestBody = Reason

// CreateMemorySpaceJSONRequestBody defines body for CreateMemorySpace for application/json ContentType.
type CreateMemorySpaceJSONRequestBody = CreateMemorySpace

// Getter for additional properties for Problem. Returns the specified
// element and whether it was found
func (a Problem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Problem
func (a *Problem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a *Problem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["request_id"]; found {
		err = json.Unmarshal(raw, &a.RequestId)
		if err != nil {
			return fmt.Errorf("error reading 'request_id': %w", err)
		}
		delete(object, "request_id")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a Problem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	if a.RequestId != nil {
		object["request_id"], err = json.Marshal(a.RequestId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'request_id': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
